name: Build Config

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build:
    name: Test
    strategy:
      matrix:
        os: [macos-latest]
        # os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Lix
        run: |
          curl -sSf -L https://install.lix.systems/lix -o /tmp/lix-install.sh
          sh /tmp/lix-install.sh install --no-confirm
          echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"

      - name: Build config
        run: |
          nix run .#build
